OFFRE_CHOICES = (
    ('neuf', 'Neuf'),
    ('louer', 'A louer'),
    ('vente', 'En vente'),
)

TYPE_CHOICES = (
    ('appartement', 'Appartement'),
    ('studio', 'Studio'),
    ('villas', 'Villas'),
    ('duplex', 'Duplex'),
)

NATURE_CHOICES = (
    ('ACD', 'ACD'),
    ('pas ACD', 'Non ACD'),
)

VILLE_CHOICES = (
    ("Abengourou", "Abengourou"),
    ("Abidjan", "Abidjan"),
    ("Aboisso", "Aboisso"),
    ("Abongoua", "Abongoua"),
    ("Adaou", "Adaou"),
    ("Adiaké", "Adiaké"),
    ("Adjouan", "Adjouan"),
    ("Adzopé", "Adzopé"),
    ("Agbaou", "Agbaou"),
    ("Agboville", "Agboville"),
    ("Agnibilékrou", "Agnibilékrou"),
    ("Ahouanou", "Ahouanou"),
    ("Ahoutoué", "Ahoutoué"),
    ("Akouédo", "Akouédo"),
    ("Akoupé", "Akoupé"),
    ("Alépé", "Alépé"),
    ("Alounamouénou", "Alounamouénou"),
    ("Ananda (Daoukro)", "Ananda (Daoukro)"), 
    ("Ananda (Daoukro)", "Ananda (Daoukro)"),  
    ("Annépé", "Annépé"), 
    ("Anyama", "Anyama"), 
    ("Arrah (Côte-d'Ivoire)", "Arrah (Côte-d'Ivoire)"),
    ("Assaoufoué", "Assaoufoué"), 
    ("Attiégouakro", "Attiégouakro"),
    ("Attoutou A", "Attoutou A"),
    ("Azaguié", "Azaguié"),
    ("Bacanda", "Bacanda"),
    ("Badikaha", "Badikaha"),
    ("Bako (Côte d'Ivoire)", "Bako (Côte d'Ivoire)"), 
    ("Baléko", "Baléko"),
    ("Bambalouma", "Bambalouma"), 
    ("Bandakagni-Sokoura", "Bandakagni-Sokoura"),
    ("Bangolo", "Bangolo"),
    ("Bangoua (Côte d'Ivoire)", "Bangoua (Côte d'Ivoire)"),
    ("Banneu", "Banneu"), 
    ("Batéguédia II", "Batéguédia II"),
    ("Bazra-Nattis", "Bazra-Nattis"),
    ("Béoumi",  "Béoumi"),  
    ("Biankouma", "Biankouma"),
    ("Bingerville", "Bingerville"), 
    ("Bongouanou", "Bongouanou"), 
    ("Bonoua (Côte d'Ivoire)", "Bonoua (Côte d'Ivoire)"),
    ("Bouaflé", "Bouaflé"), 
    ("Bouandougou", "Bouandougou"), 
    ("Bouna (Côte d'Ivoire)", "Bouna (Côte d'Ivoire)"),
    ("Boundiali (ville)", "Boundiali (ville)"), 
    ("Céchi", "Céchi"), 
    ("Dabéko", "Dabéko"), 
    ("Dabou", "Dabou"),
    ("Dabouyo", "Dabouyo"), 
    ("Dah-Zagna", "Dah-Zagna"), 
    ("Dakpadou", "Dakpadou"), 
    ("Daleu", "Daleu"),
    ("Daloa", "Daloa"),
    ("Danané", "Danané"),
    ("Danguira", "Danguira"),
    ("Daoukro", "Daoukro"),
    ("Diabo (Côte d'Ivoire)", "Diabo (Côte d'Ivoire)"),
)

"""
"Diamarakro", 
"Diangobo (Yakassé-Attobrou)", 
"Diawala", 
"Diboké", 
"Didiévi", 
"Diéouzon", 
"Digbeugnoa", 
"Dignago", 
"Dikouehipalegnoa", 
"Dimbokro", 
"Diogo (Boundiali)", 
"Dioulatiédougou", 
"Divo", 
"Djouroutou", 
"Doba (Côte d'Ivoire)", 
"Dogbo", 
"Doké", 
"Domaboué", 
"Domangbeu", 
"Douasso", 
"Doubé", 
"Doudoukou", 
"Duékoué", 
"Ebounou", 
"Elima (Côte d'Ivoire)", 
"Ery-Macouguié", 
"Fadiadougou", 
"Fahandougou", 
"Fahani", 
"Fakaha", 
"Fala (Côte d'Ivoire)", 
"Famienkro", 
"Faradiani", 
"Farandougou", 
"Ferkessédougou", 
"Fodio", 
"Fonondara", 
"Fresco (Côte d'Ivoire)", 
"Gabiadji", 
"Gagnoa", 
"Ganaoni", 
"Gbambiasso", 
"Gbangbégouiné", 
"Gbangbégouiné-Yati", 
"Gbékékro", 
"Gbéléban", 
"Gbémou", 
"Gbogui", 
"Gbon (Côte d'Ivoire)", 
"Gbongaha", 
"Gnaliepa", 
"Gnangnon", 
"Gohouo-Zagna", 
"Gomon", 
"Gonaté", 
"Gouessesso", 
"Gouiné", 
"Goulia", 
"Grabo (Côte d'Ivoire)", 
"Grand-Bassam", 
"Grand-Béréby", 
"Grand-Lahou", 
"Grand-Morié", 
"Grand-Zattry", 
"Guessabo", 
"Guéyo", 
"Guiendé", 
"Guiglo", 
"Guinglo-Tahouaké", 
"Issia", 
"Jacqueville (Côte d'Ivoire)", 
"Kahin-Zarabaon", 
"Kanakono", 
"Kaniéné", 
"Kanitélégué", 
"Kanoroba", 
"Kantélégué", 
"Kanzra", 
"Kaouara", 
"Karakoro (Côte d’Ivoire)", 
"Karakpo", 
"Kasséré", 
"Katiéré", 
"Katiola", 
"Kimbirila-Sud", 
"Koboko", 
"Kodiokofi", 
"Kofiplé", 
"Kolia", 
"Kong (Côte d'Ivoire)", 
"Kongasso", 
"Koni (Côte d'Ivoire)", 
"Konolo", 
"Korhogo", 
"Koro (Côte d'Ivoire)", 
"Kossou", 
"Kouakro", 
"Kouan-Houle", 
"Kouassi-Blékro", 
"Koukourandoumi", 
"Kounoumon", 
"Kouto", 
"Kpata", 
"Lahou-Kpanda", 
"Lakota (Côte d'Ivoire)", 
"Languibonou", 
"Lataha", 
"Liliyo", 
"Lodala", 
"Logoualé", 
"Logouhi", 
"Lohouré", 
"Lokoligou", 
"Lolobo (Yamoussoukro)", 
"Lomokankro", 
"Loplé", 
"Lossingué", 
"Lotono", 
"Loupala", 
"Loupougo", 
"Loviguié", 
"M'bahiakro",
"""